from hydra import initialize, compose
import numpy as np
import torch
from torch import Tensor as T
from scipy import stats
from sklearn import metrics
import matplotlib.pyplot as plt
# from src.attacks.prada import train_prada_scorer, train_prada_multiclass_scorer
import seaborn as sns


FEATURE_DIR = "/storage1/freewatermark/PRADA/out/features"
# FEATURE_DIR = "./data/PRADA/out/features"


# calculate the metrics based on conditional and unconditional log probabilities
def icas_score(cond, uncond, a=1.75, b=1.3, eps=1e-30, keepdims=False):
    delta = cond - uncond  # elementwise
    # delta = uncond #cond - uncond  # elementwise

    # numeric safety: clamp extreme exp arguments if needed (optional)
    # but prefer to compute exp(b * delta) carefully
    # compute token scores
    exp_term = np.exp(b * delta)
    denom = a + exp_term
    token_scores = delta / denom

    # token_scores = token_scores[:,-100:]

    icas_score = token_scores if keepdims else token_scores.mean(axis=1)
    return icas_score, token_scores


def delta(cond, uncond, keepdims=False):
    token_scores = cond - uncond
    # token_scores = token_scores[:,-100:]
    delta = token_scores if keepdims else token_scores.mean(axis=1)

    # check all-zero
    # for i, d in enumerate(delta):
    #     if np.all(d == 0):
    #         print("Warning: all-zero score detected!")
    #         print(cond[i], uncond[i])
    return delta


def cond_prob(cond, keepdims=False):
    # use the time step every 10 steps
    # step_mask = np.arange(cond.shape[1]) % 2 == 0
    # cond = cond[:, step_mask]
    return cond if keepdims else cond.mean(axis=1)


def uncond_prob(uncond, keepdims=False):
    return uncond if keepdims else uncond.mean(axis=1)


# load feature list: images generated by "generated_by", score calculated on "tested_model"
def load_feature_list(tested_model: str, generated_by: str) -> dict | None:
    """
    format of model: "{model}.{enc_name}.{gt_source}.{croponly_size}"

    e.g.:
    - "infinity_2b.ft_enc.prompt_blip2.croponly_512"
    - "llamagen_t2i_xl_256.orig_enc.."
    - "imagenet_train..prompt_blip2."
    """
    model, enc_name, gt_source, croponly_size = tested_model.split(".")
    generated_model, generated_enc, generated_source, generated_crop = generated_by.split(".")

    if not enc_name:    # Real
        return None

    if generated_enc:
        #if "infinity_2b" in generated_model:
        #    generated_model = generated_model + "_iclr"
        if "var" in generated_model or "rar" in generated_model or "sd" in generated_model:
            generated_model = generated_model.replace("_", "") + "_generated"
        else:
            generated_model = generated_model + "_generated"
    else:
        gt_source, croponly_size = generated_source, generated_crop

    folder = enc_name    
    if gt_source:
        folder += f"_{gt_source}"
    if croponly_size:
        folder += f"_{croponly_size}"

    path = f"{FEATURE_DIR}/{model}/{folder}/{generated_model}.pt"
    feature_list = torch.load(path, weights_only=False)
    return feature_list


def _load_feature_list(tested_model, generated_by):
    """
    example of tested_model: "var_20"
    example of generated_by: "rarb", "var16"
    """
    # load the config file
    with initialize(version_base=None, config_path="./conf"):
        cfg = compose(
            config_name="config",
            overrides=[
                f"+model={tested_model}",
                "+dataset=custom_paths",
                "+dataset.override_path=imagenet_train",
                "+action.name=features_extraction",
                "+attack=icas",
                "+action.device=cuda",
                f"model.dataloader={tested_model.lower().split('_')[0]}",
            ],  # This loads conf/model/{tested_model}.yaml
        )
        model_cfg = cfg.model
        attack_cfg = cfg.attack
        dataset_cfg = cfg.dataset
        config = cfg.cfg
    enc_name = config.enc_name

    # Load feature list based on tested_model and generated_by
    base_feature_dir = f"{FEATURE_DIR}/{tested_model}/{enc_name}"
    if "var" in tested_model.lower():
        # for VAR models, consider token search settings
        if model_cfg.token_optim:
            base_feature_dir += f"_token_optim_iter{model_cfg.optim_iter}_lr{model_cfg.optim_learning_rate}_scale{model_cfg.optim_stop_scale}"

    class_label_source = getattr(config, "class_label_source", "default")
    if class_label_source == "default":
        label_suffix = ""
    else:
        label_suffix = f"_labels_{class_label_source}"
    base_feature_dir += label_suffix

    prompt_source = getattr(config, "prompt_source", "default")
    if prompt_source == "default":
        prompts_suffix = ""
    else:
        prompts_suffix = f"_prompt_{prompt_source}"

    base_feature_dir += prompts_suffix

    if "imagenet" in generated_by.lower():
        path = f"{base_feature_dir}/{generated_by}.pt"
    elif generated_by.lower() == "real":
        # default real images as imagenet train set
        path = f"{base_feature_dir}/imagenet_train.pt"
    elif "llamagen" in generated_by.lower() or "infinity" in generated_by.lower():
        path = f"{base_feature_dir}/{generated_by}_generated.pt"
    else:
        path = f"{base_feature_dir}/{generated_by.replace('_', '').replace('-', '')}_generated.pt"

    # just use orig_enc
    for name in ["llamagen_t2i_xl_256", "infinity_8b"]:
        if f"{name}/ft_enc" in path:
            path = path.replace(f"{name}/ft_enc", f"{name}/orig_enc")
            break

    feature_list = torch.load(path, weights_only=False)
    return feature_list


def tokens_to_token_list_var(tokens: T) -> list[T]:
    token_list = []
    idx = 0
    patches = [1, 2, 3, 4, 5, 6, 8, 10, 13, 16]
    ps = np.array([patch**2 for patch in patches])
    for patch in ps:
        scale_target = tokens[:, idx : idx + patch] if idx else tokens[:, [0]]
        token_list.append(scale_target)
        idx += patch
    return token_list


def tokens_to_token_list_infinity(tokens: T) -> list[T]:
    token_list = []
    idx = 0
    patches = [1, 2, 4, 6, 8, 12, 16, 20, 24, 32, 40, 48, 64]
    ps = np.array(patches) ** 2
    tokens = tokens.reshape(tokens.shape[0], -1, 32)
    assert np.sum(ps) == tokens.shape[1]
    for patch in ps:
        scale_target = tokens[:, idx : idx + patch, :].reshape(tokens.shape[0], -1)
        token_list.append(scale_target)
        idx += patch
    return token_list


@torch.no_grad()
def calculate_score_from_feature_list(
    feature_list, score_type="icas", model_type="var", prada_scorer=None, keepdims=False
):
    scores = []

    # load AE and AR features
    try:
        uncond, cond = (
            feature_list["unconditional"]["log_probs"],
            feature_list["conditional"]["log_probs"],
        )
    except KeyError:
        uncond, cond = None, None
        print(f"Log probabilities not found in feature list")
    try:
        quant_losses, enc_loss_ratios = (
            feature_list["ae_loss"]["quant_losses"],
            feature_list["ae_loss"]["enc_loss_ratios"],
        )
    except KeyError:
        quant_losses, enc_loss_ratios = None, None
        print("AE loss not found in feature list")

    # calculate scores based on the specified score type
    match score_type:
        case "icas":
            scores, token_scores = icas_score(
                np.stack(cond), np.stack(uncond), keepdims=keepdims
            )
            print(f"shape of scores: {scores.shape}")
        case "delta":
            scores = delta(np.stack(cond), np.stack(uncond), keepdims=keepdims)
            print(f"shape of scores: {scores.shape}")
        case "cond":
            scores = cond_prob(np.stack(cond), keepdims=keepdims)
            print(f"shape of scores: {scores.shape}")
        case "uncond":
            scores = uncond_prob(np.stack(uncond), keepdims=keepdims)
            print(f"shape of scores: {scores.shape}")
        case "prada":
            assert prada_scorer is not None, "Prada scorer not initialized"
            # print(len(cond), len(uncond))
            if "var" in model_type.lower():
                cond = tokens_to_token_list_var(torch.from_numpy(np.stack(cond)).cuda())
                uncond = tokens_to_token_list_var(
                    torch.from_numpy(np.stack(uncond)).cuda()
                )
            elif "infinity" in model_type.lower():
                cond = tokens_to_token_list_infinity(
                    torch.from_numpy(np.stack(cond)).cuda()
                )
                uncond = tokens_to_token_list_infinity(
                    torch.from_numpy(np.stack(uncond)).cuda()
                )
            else:
                cond = [torch.from_numpy(np.stack(cond)).cuda()]
                uncond = [torch.from_numpy(np.stack(uncond)).cuda()]
            scores = prada_scorer(cond, uncond)
            scores = scores.detach().cpu().numpy()
        case "quant":
            quant_losses = np.stack(quant_losses)
            scores = -quant_losses
        case "enc":
            enc_loss_ratios = np.stack(enc_loss_ratios)
            scores = -enc_loss_ratios
        case "ae":
            if "sd" in model_type.lower():
                # do not use QuantLoss for SD
                enc_loss_ratios = np.stack(enc_loss_ratios)
                # check extreme values
                extreme_indices = np.where(
                    (enc_loss_ratios > 10) | (enc_loss_ratios < 0.01)
                )[0]
                if len(extreme_indices) > 0:
                    print(
                        f"Warning: extreme enc_loss_ratios detected at indices {extreme_indices}"
                    )
                scores = -enc_loss_ratios
            elif "infinity" in model_type.lower():  # Only use quantloss for infinity
                quant_losses = np.stack(quant_losses)
                scores = -quant_losses
            else:
                quant_losses = np.stack(quant_losses)
                enc_loss_ratios = np.stack(enc_loss_ratios)
                scores = -quant_losses * enc_loss_ratios

        case _:
            raise ValueError(f"Unknown score type: {score_type}")

    if "sd" in model_type.lower() and score_type in [
        "icas",
        "delta",
        "cond",
        "uncond",
        "prada",
    ]:
        scores = -scores  # reverse the sign for SD models
    return np.array(scores)


def split_feature_list_for_calibration_and_test(feature_list, calibration_size=250):
    # feature list is a dict of dicts
    calibration_feature_list = {}
    test_feature_list = {}
    for key in feature_list.keys():
        calibration_feature_list[key] = {}
        test_feature_list[key] = {}
        for subkey in feature_list[key].keys():
            calibration_feature_list[key][subkey] = feature_list[key][subkey][
                :calibration_size
            ]
            test_feature_list[key][subkey] = feature_list[key][subkey][
                calibration_size:
            ]
    return calibration_feature_list, test_feature_list


def evaluation(tested_model, generated_by, score_metric="icas"):
    print(
        f"Evaluating {tested_model} tested on images generated by {generated_by} using {score_metric} metric"
    )

    feature_list = load_feature_list(tested_model, generated_by)
    non_belonging_scores = calculate_score_from_feature_list(
        feature_list, score_type=score_metric, model_type=tested_model
    )

    belonging_feature_list = load_feature_list(tested_model, tested_model)
    belonging_scores = calculate_score_from_feature_list(
        belonging_feature_list, score_type=score_metric, model_type=tested_model
    )

    all_labels = np.concatenate(
        [-np.ones(len(non_belonging_scores)), np.ones(len(belonging_scores))]
    )
    all_scores = np.concatenate([non_belonging_scores, belonging_scores])

    fpr, tpr, threshold = metrics.roc_curve(all_labels, all_scores)
    auc = metrics.auc(fpr, tpr)
    acc = np.max(1 - (fpr + (1 - tpr)) / 2)

    idx = np.where(fpr <= 0.01)[0][-1]
    threshold_at_1fpr = threshold[idx]
    tpr_at_1fpr = tpr[idx]

    print(
        f"Threshold at 1% FPR: {threshold_at_1fpr:.4f}, AUC: {auc:.4f}, Acc: {acc:.4f}, TPR at 1% FPR: {tpr_at_1fpr:.4f}"
    )

    # Plot ICAS score distribution
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.hist(
        non_belonging_scores,
        bins=100,
        alpha=0.6,
        label=f"Non-belonging ({generated_by})",
        color="red",
        edgecolor="black",
    )
    ax.hist(
        belonging_scores,
        bins=100,
        alpha=0.6,
        label=f"Belonging ({tested_model})",
        color="blue",
        edgecolor="black",
    )
    ax.axvline(
        threshold_at_1fpr,
        color="green",
        linestyle="--",
        linewidth=2,
        label=f"Threshold at 1% FPR: {threshold_at_1fpr:.4f} (TPR: {tpr_at_1fpr:.4f}, AUC: {auc:.4f})",
    )
    ax.set_xlabel("Score")
    ax.set_ylabel("Frequency")
    ax.set_title(
        f"Score Distribution - {tested_model} vs {generated_by} with {score_metric.upper()}"
    )
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    return threshold_at_1fpr, auc, acc, tpr_at_1fpr


def evaluation_comparison(tested_model, generated_by):
    """
    Generate side-by-side comparison plots for delta and ICAS score distributions
    """

    feature_list = load_feature_list(tested_model, generated_by)

    non_belonging_scores_delta = []
    non_belonging_scores_icas = []

    for uncond, cond in zip(
        feature_list["unconditional"]["log_probs"],
        feature_list["conditional"]["log_probs"],
    ):
        delta_score = delta(np.array(cond), np.array(uncond))
        icas_score_val, _ = icas_score(np.array(cond), np.array(uncond))
        non_belonging_scores_delta.append(delta_score)
        non_belonging_scores_icas.append(icas_score_val)

    belonging_feature_list = load_feature_list(tested_model, tested_model)

    belonging_scores_delta = []
    belonging_scores_icas = []

    for uncond, cond in zip(
        belonging_feature_list["unconditional"]["log_probs"],
        belonging_feature_list["conditional"]["log_probs"],
    ):
        delta_score = delta(np.array(cond), np.array(uncond))
        icas_score_val, _ = icas_score(np.array(cond), np.array(uncond))
        belonging_scores_delta.append(delta_score)
        belonging_scores_icas.append(icas_score_val)

    # Create figure with two subplots
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))

    # Plot 1: Delta scores
    all_labels = np.concatenate(
        [
            np.zeros(len(non_belonging_scores_delta)),
            np.ones(len(belonging_scores_delta)),
        ]
    )
    all_scores_delta = np.concatenate(
        [non_belonging_scores_delta, belonging_scores_delta]
    )

    fpr_delta, tpr_delta, threshold_delta = metrics.roc_curve(
        all_labels, all_scores_delta
    )
    auc_delta = metrics.auc(fpr_delta, tpr_delta)
    acc_delta = np.max(1 - (fpr_delta + (1 - tpr_delta)) / 2)

    idx_delta = np.where(fpr_delta <= 0.01)[0][-1]
    threshold_at_1fpr_delta = threshold_delta[idx_delta]
    tpr_at_1fpr_delta = tpr_delta[idx_delta]

    axes[0].hist(
        non_belonging_scores_delta,
        bins=30,
        alpha=0.6,
        label=f"Non-belonging ({generated_by})",
        color="red",
        edgecolor="black",
    )
    axes[0].hist(
        belonging_scores_delta,
        bins=30,
        alpha=0.6,
        label=f"Belonging ({tested_model})",
        color="blue",
        edgecolor="black",
    )
    axes[0].axvline(
        threshold_at_1fpr_delta,
        color="green",
        linestyle="--",
        linewidth=2,
        label=f"Threshold at 1% FPR: {threshold_at_1fpr_delta:.4f}",
    )
    axes[0].set_xlabel("Delta Score")
    axes[0].set_ylabel("Frequency")
    axes[0].set_title(
        f"Delta Score Distribution\nAUC: {auc_delta:.4f}, Acc: {acc_delta:.4f}, TPR@1%FPR: {tpr_at_1fpr_delta:.4f}"
    )
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Plot 2: ICAS scores
    all_scores_icas = np.concatenate([non_belonging_scores_icas, belonging_scores_icas])

    fpr_icas, tpr_icas, threshold_icas = metrics.roc_curve(all_labels, all_scores_icas)
    auc_icas = metrics.auc(fpr_icas, tpr_icas)
    acc_icas = np.max(1 - (fpr_icas + (1 - tpr_icas)) / 2)

    idx_icas = np.where(fpr_icas <= 0.01)[0][-1]
    threshold_at_1fpr_icas = threshold_icas[idx_icas]
    tpr_at_1fpr_icas = tpr_icas[idx_icas]

    axes[1].hist(
        non_belonging_scores_icas,
        bins=30,
        alpha=0.6,
        label=f"Non-belonging ({generated_by})",
        color="red",
        edgecolor="black",
    )
    axes[1].hist(
        belonging_scores_icas,
        bins=30,
        alpha=0.6,
        label=f"Belonging ({tested_model})",
        color="blue",
        edgecolor="black",
    )
    axes[1].axvline(
        threshold_at_1fpr_icas,
        color="green",
        linestyle="--",
        linewidth=2,
        label=f"Threshold at 1% FPR: {threshold_at_1fpr_icas:.4f}",
    )
    axes[1].set_xlabel("ICAS Score")
    axes[1].set_ylabel("Frequency")
    axes[1].set_title(
        f"ICAS Score Distribution\nAUC: {auc_icas:.4f}, Acc: {acc_icas:.4f}, TPR@1%FPR: {tpr_at_1fpr_icas:.4f}"
    )
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

    # Print summary
    print(f"\n{'='*60}")
    print(f"Comparison: {tested_model} vs {generated_by}")
    print(f"{'='*60}")
    print(f"{'Metric':<20} {'Delta':<20} {'ICAS':<20}")
    print(f"{'-'*60}")
    print(f"{'AUC':<20} {auc_delta:<20.4f} {auc_icas:<20.4f}")
    print(f"{'Accuracy':<20} {acc_delta:<20.4f} {acc_icas:<20.4f}")
    print(f"{'TPR@1%FPR':<20} {tpr_at_1fpr_delta:<20.4f} {tpr_at_1fpr_icas:<20.4f}")
    print(
        f"{'Threshold@1%FPR':<20} {threshold_at_1fpr_delta:<20.4f} {threshold_at_1fpr_icas:<20.4f}"
    )
    print(f"{'='*60}\n")


def calculate_score_for_prada(
    tested_model, generated_by, calibration_set="imagenet_val", prada_scorer_dict=dict()
):
    lr = 1e-2
    weight_decay = 0.0001
    batch_size = 1000
    epochs = 100
    calibration_size = 250
    calibration_set = "imagenet_val"

    prada_scorer_dict.setdefault(tested_model, {})
    if calibration_set not in prada_scorer_dict[tested_model]:
        # train prada scorer for this tested_model
        belonging_feature_list = load_feature_list(tested_model, tested_model)
        non_belonging_feature_list = load_feature_list(tested_model, calibration_set)
        calibration_belonging, test_belonging = (
            split_feature_list_for_calibration_and_test(
                belonging_feature_list, calibration_size=calibration_size
            )
        )
        calibration_non_belonging, _ = split_feature_list_for_calibration_and_test(
            non_belonging_feature_list, calibration_size=calibration_size
        )
        prada_scorer = train_prada_scorer(
            calibration_belonging,
            calibration_non_belonging,
            lr=lr,
            weight_decay=weight_decay,
            batch_size=batch_size,
            epochs=epochs,
            model_type=tested_model,
        )
        prada_scorer_dict[tested_model][calibration_set] = prada_scorer
    else:
        print(
            f"Using existing Prada scorer for {tested_model} calibrated on {calibration_set}"
        )
        prada_scorer = prada_scorer_dict[tested_model][calibration_set]
    belonging_feature_list = load_feature_list(tested_model, tested_model)
    # non_belonging_feature_list = load_feature_list(tested_model, calibration_set)
    calibration_belonging, test_belonging = split_feature_list_for_calibration_and_test(
        belonging_feature_list, calibration_size=calibration_size
    )
    # calibration_non_belonging, _ = split_feature_list_for_calibration_and_test(non_belonging_feature_list, calibration_size=calibration_size)

    non_belonging_feature_list = load_feature_list(tested_model, generated_by)
    _, test_non_belonging = split_feature_list_for_calibration_and_test(
        non_belonging_feature_list, calibration_size=calibration_size
    )
    belonging_scores = calculate_score_from_feature_list(
        test_belonging,
        score_type="prada",
        prada_scorer=prada_scorer,
        model_type=tested_model,
    )
    non_belonging_scores = calculate_score_from_feature_list(
        test_non_belonging,
        score_type="prada",
        prada_scorer=prada_scorer,
        model_type=tested_model,
    )
    return belonging_scores, non_belonging_scores


def calculate_score_for_prada_multiclass(
    tested_model,
    model_list,
    calibration_set="imagenet_val",
    calibration_size=250,
    lr=1e-2,
    weight_decay=0.0001,
    batch_size=1000,
    epochs=100,
):
    """
    Train a multiclass PRADA scorer on m calibration sets and evaluate on m test sets.

    Args:
        tested_model: The model used to compute features (e.g., "var_16")
        model_list: List of m model names to use as classes (e.g., ["var_16", "var_20", "var_24", "var_30"])
        calibration_set: Name of the calibration set for non-belonging (not used in multiclass)
        calibration_size: Number of samples for calibration per class
        lr, weight_decay, batch_size, epochs: Training hyperparameters

    Returns:
        prada_scorer: Trained multiclass PRADA scorer
        test_sets: List of test feature sets for each class
        class_names: List of class names corresponding to model_list
    """
    calibration_sets = []
    test_sets = []

    # Load calibration and test data for each class
    for model_name in model_list:
        print(f"Loading features for class: {model_name}")
        feature_list = load_feature_list(tested_model, model_name)
        calibration_set_data, test_set_data = (
            split_feature_list_for_calibration_and_test(
                feature_list, calibration_size=calibration_size
            )
        )
        calibration_sets.append(calibration_set_data)
        test_sets.append(test_set_data)

    # Train multiclass scorer
    print(f"\nTraining multiclass PRADA scorer with {len(model_list)} classes...")
    prada_scorer = train_prada_multiclass_scorer(
        calibration_sets,
        lr=lr,
        weight_decay=weight_decay,
        batch_size=batch_size,
        epochs=epochs,
        model_type=tested_model,
    )

    return prada_scorer, test_sets, model_list


def evaluate_prada_multiclass(prada_scorer, test_sets, class_names, model_type="var"):
    """
    Evaluate multiclass PRADA scorer on test sets.

    Args:
        prada_scorer: Trained PradaMulticlass model
        test_sets: List of test feature sets for each class
        class_names: List of class names
        model_type: Model type string

    Returns:
        confusion_matrix: m x m confusion matrix (rows=true, cols=predicted)
        accuracy: Overall accuracy
        per_class_accuracy: Accuracy per class
    """
    num_classes = len(class_names)
    confusion_matrix = np.zeros((num_classes, num_classes))

    prada_scorer.eval()

    with torch.no_grad():
        for true_class_idx, test_set in enumerate(test_sets):
            # Prepare test data
            cond = test_set["conditional"]["log_probs"]
            uncond = test_set["unconditional"]["log_probs"]

            # Convert to tensor format
            if "var" in model_type.lower():
                cond_tensor = tokens_to_token_list_var(
                    torch.from_numpy(np.stack(cond)).cuda()
                )
                uncond_tensor = tokens_to_token_list_var(
                    torch.from_numpy(np.stack(uncond)).cuda()
                )
            elif "infinity" in model_type.lower():
                cond_tensor = tokens_to_token_list_infinity(
                    torch.from_numpy(np.stack(cond)).cuda()
                )
                uncond_tenosr = tokens_to_token_list_infinity(
                    torch.from_numpy(np.stack(uncond)).cuda()
                )
            else:
                cond_tensor = [torch.from_numpy(np.stack(cond)).cuda()]
                uncond_tensor = [torch.from_numpy(np.stack(uncond)).cuda()]

            # Get predictions
            predictions = prada_scorer.predict(cond_tensor, uncond_tensor)
            predictions = predictions.cpu().numpy()

            # Update confusion matrix
            for pred in predictions:
                confusion_matrix[true_class_idx, pred] += 1

    # Normalize to percentages
    row_sums = confusion_matrix.sum(axis=1, keepdims=True)
    confusion_matrix_pct = (confusion_matrix / row_sums) * 100

    # Calculate accuracies
    total_correct = np.trace(confusion_matrix)
    total_samples = confusion_matrix.sum()
    accuracy = total_correct / total_samples

    per_class_accuracy = np.diag(confusion_matrix) / confusion_matrix.sum(axis=1)

    return confusion_matrix_pct, accuracy, per_class_accuracy


def plot_multiclass_confusion_matrix(
    confusion_matrix, class_names, title="Multiclass PRADA Attribution"
):
    """Plot confusion matrix for multiclass PRADA"""
    fig, ax = plt.subplots(figsize=(10, 8))

    # Create annotations
    annot = np.empty_like(confusion_matrix, dtype=object)
    for i in range(confusion_matrix.shape[0]):
        for j in range(confusion_matrix.shape[1]):
            annot[i, j] = f"{confusion_matrix[i, j]:.1f}"

    sns.heatmap(
        confusion_matrix,
        annot=annot,
        fmt="",
        cmap="Blues",
        xticklabels=class_names,
        yticklabels=class_names,
        vmin=0,
        vmax=100,
        cbar_kws={"label": "Attribution %"},
        ax=ax,
        square=True,
    )

    ax.set_xlabel("Predicted Class", fontsize=12)
    ax.set_ylabel("True Class", fontsize=12)
    ax.set_title(title, fontsize=14, pad=20)

    plt.tight_layout()
    plt.show()

    return fig


def create_attribution_matrix(
    models,
    score_metric="icas",
    use_imagenet_train=False,
    calibration_set="imagenet_val",
):
    """
    Create attribution confusion matrix

    Args:
        models: List of model names (e.g., ['HMAR-d20', 'HMAR-d30', ...])
        score_metric: 'icas' or 'delta'
        use_imagenet_train: If True, use imagenet_train as belonging set
    """
    n_models = len(models)
    confusion_matrix = np.zeros((n_models, n_models))
    std_matrix = np.zeros((n_models, n_models))

    # For each real/true class (row)
    for i, true_model in enumerate(models):
        print(f"Processing true class: {true_model}")

        try:
            # We need to load features computed with each model as the tested_model
            # For each candidate model, we need features computed by that model
            test_scores_dict = {}
            n_samples = None

            # Compute scores against each model (predicted class)
            for j, pred_model in enumerate(models):
                print(f"  Computing scores for {true_model} against {pred_model}")
                if pred_model.lower() == "real":
                    test_scores_dict[pred_model] = np.array([])
                    continue
                # Load test features computed by pred_model on true_model's data

                try:
                    # Compute test scores (how well test samples match this model)
                    if score_metric == "prada":
                        belonging_scores, non_belonging_scores = (
                            calculate_score_for_prada(
                                tested_model=pred_model,
                                generated_by=true_model,
                                calibration_set=calibration_set,
                            )
                        )
                        test_scores = non_belonging_scores
                    else:
                        test_features = load_feature_list(pred_model, true_model)
                        test_scores = calculate_score_from_feature_list(
                            test_features,
                            score_type=score_metric,
                            model_type=pred_model,
                        )

                    test_scores_dict[pred_model] = test_scores

                    if n_samples is None:
                        n_samples = len(test_scores)

                except Exception as e:
                    print(f"    Warning: Could not load features for {pred_model}: {e}")
                    test_scores_dict[pred_model] = np.array([])

            # For each test sample, attribute to model with highest score
            if n_samples is None or n_samples == 0:
                print(f"  No samples found for {true_model}")
                continue

            attributions = []
            real_idx = models.index("Real") if "Real" in models else -1

            for sample_idx in range(n_samples):
                sample_scores = []
                valid_scores = []

                for k, pred_model in enumerate(models):
                    if pred_model.lower() == "real":
                        # Real class placeholder, will be determined by threshold
                        sample_scores.append(-np.inf)
                    elif len(test_scores_dict[pred_model]) > sample_idx:
                        score = test_scores_dict[pred_model][sample_idx]
                        sample_scores.append(score)
                        valid_scores.append(score)
                    else:
                        sample_scores.append(-np.inf)

                # Check if all valid scores are below 0
                # If so, classify as Real; otherwise, take the highest score
                if len(valid_scores) > 0 and all(s < 0 for s in valid_scores):
                    # All scores negative -> classify as Real
                    if real_idx >= 0:
                        predicted_idx = real_idx
                    else:
                        predicted_idx = np.argmax(sample_scores)
                else:
                    # At least one positive score -> attribute to model with highest score
                    predicted_idx = np.argmax(sample_scores)

                attributions.append(predicted_idx)

            # Count attributions for confusion matrix
            attributions = np.array(attributions)
            for j in range(n_models):
                count = np.sum(attributions == j)
                percentage = (count / n_samples) * 100 if n_samples > 0 else 0
                confusion_matrix[i, j] = percentage

                # Calculate std (bootstrap estimate)
                if n_samples > 0:
                    std_matrix[i, j] = np.sqrt(
                        percentage * (100 - percentage) / n_samples
                    )

        except Exception as e:
            print(f"  Error processing {true_model}: {e}")

    return confusion_matrix, std_matrix


def plot_attribution_matrix(confusion_matrix, std_matrix, models: dict[str, str], score_metric="icas"):
    """Plot the attribution confusion matrix"""
    fig, ax = plt.subplots(figsize=(12, 10))

    # Create annotations with percentage ± std
    annot = np.empty_like(confusion_matrix, dtype=object)
    for i in range(confusion_matrix.shape[0]):
        for j in range(confusion_matrix.shape[1]):
            annot[i, j] = f"{confusion_matrix[i, j]:.1f}\n±{std_matrix[i, j]:.1f}"

    generator_models = [k for k,v in models.items() if v.split(".")[1]]

    # Plot heatmap
    sns.heatmap(
        confusion_matrix,
        annot=annot,
        fmt="",
        cmap="Blues",
        xticklabels=generator_models + ["Outlier"],
        yticklabels=list(models.keys()),
        vmin=0,
        vmax=100,
        cbar_kws={"label": "Attribution %"},
        ax=ax,
        square=True,
    )

    ax.set_xlabel("Predicted Class", fontsize=12)
    ax.set_ylabel("True Class", fontsize=12)
    ax.set_title(
        f"Model Attribution Confusion Matrix ({score_metric.upper()})",
        fontsize=14,
        pad=20,
    )

    plt.tight_layout()
    plt.show()

    return fig


def grubbs_test(sample, population_data, alpha=0.05):
    """
    Perform one-sided (right-sided) Grubbs' test to check if 'sample' is a maximum outlier in 'population_data'.
    """
    # Combine sample with data
    bonferroni = True
    combined_data = np.array(population_data)
    n = len(combined_data)
    mean = np.mean(combined_data)
    std = np.std(combined_data)
    # Calculate G statistic for right-sided test (maximum outlier)
    # G = (sample - mean) / std
    G = (sample - mean) / std
    # print(G)
    # If sample is less than mean, it cannot be a right-sided outlier

    # Calculate critical value for one-sided test
    # t_crit = t_dist.ppf(1 - alpha / n, n - 2)
    if bonferroni:
        alpha = alpha / n
    t_crit = stats.t.ppf(alpha, n - 2)
    G_crit = ((n - 1) / np.sqrt(n)) * np.sqrt(t_crit**2 / (n - 2 + t_crit**2))
    is_belonging = G < G_crit
    # Calculate p-value for one-sided test
    max_G = (n - 1) / np.sqrt(n)
    term = (G**2 * n) / ((n - 1) ** 2)
    t_squared = (term * (n - 2)) / (1 - term)
    # if t_squared < 0:
    #     print("Warning: negative t_squared value encountered in Grubbs' test p-value calculation.")
    #     print(f"sample: {sample}, mean: {mean}, std: {std}, G: {G}, n: {n}")

    # t_stat = np.sqrt(t_squared)
    # # One-sided p-value for right tail (high values)
    # p_value = (1 - stats.t.cdf(t_stat, n - 2))
    # if bonferroni:
    #     p_value = min(p_value * n, 1.0)
    # p_value = min(p_value, 1.0)

    p_value = None

    return p_value, is_belonging, G


def create_attribution_matrix_with_ae(
    models,
    score_metric="icas",
    use_imagenet_train=False,
    calibration_set="imagenet_val",
    calibration_size=250,
    threshold_p_value=0.01,
):
    """
    Create attribution confusion matrix

    Args:
        models: List of model names (e.g., ['HMAR-d20', 'HMAR-d30', ...])
        score_metric: 'icas' or 'delta'
        use_imagenet_train: If True, use imagenet_train as belonging set
    """
    real_models = {x for x in models if not x.split(".")[1]}

    n_models = len(models)
    real_idx = n_models - len(real_models)
    confusion_matrix = np.zeros((n_models, real_idx + 1))
    std_matrix = np.zeros((n_models, real_idx + 1))
    ae_calibration_sets = {}
    ar_calibration_sets = {}

    # Load features for calibration
    for i, pred_model in enumerate(models):
        if pred_model in real_models:
            continue
        ae_belonging_feature_list = load_feature_list(pred_model, pred_model)
        calibration_belonging, _ = split_feature_list_for_calibration_and_test(
            ae_belonging_feature_list, calibration_size=calibration_size
        )
        ae_calibration_sets[pred_model] = -calculate_score_from_feature_list(
            calibration_belonging, score_type="ae", model_type=pred_model
        )  # !!reverse AE score sign for attribution

        ar_calibration_sets[pred_model] = calculate_score_from_feature_list(calibration_belonging, score_type=score_metric, model_type=pred_model)

    # For each real/true class (row)
    for i, true_model in enumerate(models):
        print(f"Processing true class: {true_model}")

        try:
            # We need to load features computed with each candidate model
            ae_test_scores_dict, ar_test_scores_dict = {}, {}
            for j, pred_model in enumerate(models):
                print(f"  Computing scores for {true_model} against {pred_model}")
                if pred_model in real_models:
                    ae_test_scores_dict[pred_model], ar_test_scores_dict[pred_model] = (
                        np.array([]),
                        np.array([]),
                    )
                    continue
                # Load test features computed by pred_model on true_model's data
                try:
                    # load features and split into calibration and test sets
                    all_features = load_feature_list(f"{pred_model}", true_model)
                    _, test_features = split_feature_list_for_calibration_and_test(
                        all_features, calibration_size=calibration_size
                    )
                    # Compute AE test scores
                    ae_test_scores = -calculate_score_from_feature_list(
                        test_features, score_type="ae", model_type=pred_model
                    )  # !!reverse AE score sign for attribution
                    # Compute AR test scores
                    if score_metric == "prada":
                        belonging_scores, non_belonging_scores = (
                            calculate_score_for_prada(
                                tested_model=pred_model,
                                generated_by=true_model,
                                calibration_set=calibration_set,
                            )
                        )
                        ar_test_scores = non_belonging_scores
                    else:
                        ar_test_scores = calculate_score_from_feature_list(
                            test_features,
                            score_type=score_metric,
                            model_type=pred_model,
                        )

                    ae_test_scores_dict[pred_model] = ae_test_scores
                    ar_test_scores_dict[pred_model] = ar_test_scores

                except Exception as e:
                    print(f"    Warning: Could not load features for {pred_model}: {e}")
                    ae_test_scores_dict[pred_model], ar_test_scores_dict[pred_model] = (
                        np.array([]),
                        np.array([]),
                    )
            # For each test sample, attribute to model with highest score
            n_samples = len(ae_test_scores_dict[models[0]]) if models else 0
            print(f"Loaded {n_samples} samples for {true_model}")
            assert len(ae_test_scores_dict[models[0]]) == len(
                ar_test_scores_dict[models[0]]
            ), "AE and AR test scores must have the same length"
            attributions = []

            for sample_idx in range(n_samples):
                # for a given image, determine attribution based on both AE and AR scores
                ar_sample_scores = []
                ae_suspect_model_idx = []

                for k, pred_model in enumerate(models):
                    if pred_model in real_models:
                        continue
                    else:
                        assert (
                            len(ae_test_scores_dict[pred_model]) > sample_idx
                            and len(ar_test_scores_dict[pred_model]) > sample_idx
                        ), f"Not enough test scores for model {pred_model}"
                        """AE attribution with Grubbs' test"""
                        ae_score = ae_test_scores_dict[pred_model][sample_idx]
                        calibration_scores = ae_calibration_sets[pred_model]
                        p_value, is_belonging, G = grubbs_test(
                            ae_score, calibration_scores, alpha=threshold_p_value
                        )
                        if is_belonging:
                            ae_suspect_model_idx.append(k)
                            ar_score = ar_test_scores_dict[pred_model][sample_idx]
                            # p_value, is_belonging, G = grubbs_test(-ar_score, -ar_calibration_sets[pred_model], alpha=threshold_p_value)
                            # ar_score = -G
                            # calibration = sorted(ar_calibration_sets[pred_model])
                            # data = np.array(calibration)
                            # mean = np.mean(data)
                            # std = np.std(data)
                            # ar_score = ar_score - mean
                            ar_sample_scores.append(ar_score)
                if len(ar_sample_scores) == 0:
                    # No AE suspect models, classify as Real
                    predicted_idx = real_idx
                else:
                    """AR attribution"""
                    # take the model with highest AR score among AE suspect models
                    predicted_idx = ae_suspect_model_idx[np.argmax(ar_sample_scores)]

                attributions.append(predicted_idx)

            # Count attributions for confusion matrix
            attributions = np.array(attributions)
            for j in range(confusion_matrix.shape[1]):
                count = np.sum(attributions == j)
                percentage = (count / n_samples) * 100 if n_samples > 0 else 0
                confusion_matrix[i, j] = percentage

                # Calculate std (bootstrap estimate)
                if n_samples > 0:
                    std_matrix[i, j] = np.sqrt(
                        percentage * (100 - percentage) / n_samples
                    )

        except Exception as error:
            print(f"  Error processing {true_model}: {error}")

    return confusion_matrix, std_matrix


def create_and_plot_attribution_matrix(models: dict[str,str], score_metric="icas", with_ae=True):
    print(
        f"Creating attribution matrix. Including AE: {with_ae}, Score metric: {score_metric}"
    )
    if with_ae:
        conf_matrix, std_matrix = create_attribution_matrix_with_ae(
            list(models.values()), score_metric=score_metric, use_imagenet_train=False
        )
    else:
        conf_matrix, std_matrix = create_attribution_matrix(
            list(models.values()), score_metric=score_metric, use_imagenet_train=False
        )
    print("\nPlotting confusion matrix...")
    plot_attribution_matrix(
        conf_matrix,
        std_matrix,
        models,
        score_metric=f"{score_metric} w/{'o'[int(with_ae):]} AE",
    )
    accuracy = np.trace(conf_matrix) / len(models)
    print(f"\nOverall Attribution Accuracy: {accuracy:.2f}%")


def compute_tpr_at_fpr(belonging_scores, non_belonging_scores, target_fpr=0.01):
    """
    Compute TPR@1%FPR for a specific tested_model vs generated_by combination

    Args:
        belonging_scores: Scores from the model evaluating its own images
        non_belonging_scores: Scores from the model evaluating generated images
        score_metric: 'icas' or 'delta'
        target_fpr: Target false positive rate (default 0.01 for 1%)

    Returns:
        tpr_at_target_fpr, auc, acc, threshold
    """

    # Combine scores and labels
    # Label 0 = non-belonging, Label 1 = belonging
    all_labels = np.concatenate(
        [np.zeros(len(non_belonging_scores)), np.ones(len(belonging_scores))]
    )
    all_scores = np.concatenate([non_belonging_scores, belonging_scores])

    # Compute ROC curve
    fpr, tpr, thresholds = metrics.roc_curve(all_labels, all_scores)
    auc = metrics.auc(fpr, tpr)
    acc = np.max(1 - (fpr + (1 - tpr)) / 2)

    # Find TPR at target FPR
    idx = np.where(fpr <= target_fpr)[0]
    if len(idx) > 0:
        idx = idx[-1]
        tpr_at_target = tpr[idx]
        threshold_at_target = thresholds[idx]
    else:
        tpr_at_target = 0.0
        threshold_at_target = np.inf

    return tpr_at_target, auc, acc, threshold_at_target


def create_tpr_table(
    models,
    score_metric="icas",
    target_fpr=0.01,
    calibration_set="imagenet_val",
):
    """
    Create a table of TPR@FPR for all model combinations

    Args:
        models: List of model names
        score_metric: 'icas' or 'delta'
        target_fpr: Target false positive rate

    Returns:
        DataFrame with TPR values, AUC values, and combined matrix
    """
    n_models = len(models)
    tpr_matrix = np.zeros((n_models, n_models))
    auc_matrix = np.zeros((n_models, n_models))

    print(f"Computing TPR@{target_fpr*100:.0f}%FPR for all combinations...\n")

    # For each tested model (belonging class) - rows
    for i, tested_model in enumerate(models):
        if (
            tested_model.lower() == "real"
            or tested_model.lower() == "taming"
            or tested_model.lower() == "llamagenl"
            or "imagenet" in tested_model.lower()
        ):
            print(f"Skipping model: {tested_model}\n")
            continue

        print(f"Testing model: {tested_model}")
        # execute only if prada_scorer_dict[tested_model][calibration_set] exists

        # Against each generated_by model (non-belonging class) - columns
        for j, generated_by in enumerate(models):
            if score_metric == "prada":
                # prada_scorer_dict.setdefault(tested_model, {})
                # if calibration_set not in prada_scorer_dict[tested_model]:
                #     # train prada scorer for this tested_model
                #     belonging_feature_list = load_feature_list(tested_model, tested_model)
                #     non_belonging_feature_list = load_feature_list(tested_model, calibration_set)
                #     calibration_belonging, test_belonging = split_feature_list_for_calibration_and_test(belonging_feature_list, calibration_size=calibration_size)
                #     calibration_non_belonging, _ = split_feature_list_for_calibration_and_test(non_belonging_feature_list, calibration_size=calibration_size)
                #     prada_scorer = train_prada_scorer(calibration_belonging, calibration_non_belonging, lr=lr, weight_decay=weight_decay, batch_size=batch_size, epochs=epochs, model_type=tested_model)
                #     prada_scorer_dict[tested_model][calibration_set] = prada_scorer
                # else:
                #     print(f"Using existing Prada scorer for {tested_model} calibrated on {calibration_set}")
                #     prada_scorer = prada_scorer_dict[tested_model][calibration_set]
                # belonging_feature_list = load_feature_list(tested_model, tested_model)
                # # non_belonging_feature_list = load_feature_list(tested_model, calibration_set)
                # calibration_belonging, test_belonging = split_feature_list_for_calibration_and_test(belonging_feature_list, calibration_size=calibration_size)
                # # calibration_non_belonging, _ = split_feature_list_for_calibration_and_test(non_belonging_feature_list, calibration_size=calibration_size)

                # non_belonging_feature_list = load_feature_list(tested_model, generated_by)
                # _, test_non_belonging = split_feature_list_for_calibration_and_test(non_belonging_feature_list, calibration_size=calibration_size)
                # belonging_scores = calculate_score_from_feature_list(test_belonging, score_type="prada", prada_scorer=prada_scorer, model_type=tested_model)
                # non_belonging_scores = calculate_score_from_feature_list(test_non_belonging, score_type="prada", prada_scorer=prada_scorer, model_type=tested_model)

                belonging_scores, non_belonging_scores = calculate_score_for_prada(
                    tested_model, generated_by, calibration_set=calibration_set
                )
            else:
                # Load non-belonging data (tested_model evaluating generated_by's images)
                try:
                    non_belonging_features = load_feature_list(
                        tested_model, generated_by
                    )
                    non_belonging_scores = calculate_score_from_feature_list(
                        non_belonging_features,
                        score_type=score_metric,
                        model_type=tested_model,
                    )
                except Exception as e:
                    print(
                        f"Error loading non-belonging data for {tested_model} vs {generated_by}: {e}"
                    )
                    return None, None, None, None

                # Load belonging data (tested_model evaluating its own images)
                try:
                    belonging_features = load_feature_list(tested_model, tested_model)
                    belonging_scores = calculate_score_from_feature_list(
                        belonging_features,
                        score_type=score_metric,
                        model_type=tested_model,
                    )
                except Exception as e:
                    print(f"Error loading belonging data for {tested_model}: {e}")
                    return None, None, None, None

            if i == j:
                # Diagonal: same model (100% TPR expected)
                tpr_matrix[i, j] = 100.0
                auc_matrix[i, j] = 100.0
                print(f"  vs {generated_by}: DIAGONAL (skipped)")
            else:
                tpr, auc, acc, threshold = compute_tpr_at_fpr(
                    belonging_scores, non_belonging_scores, target_fpr
                )

                if tpr is not None:
                    tpr_matrix[i, j] = tpr * 100  # Convert to percentage
                    auc_matrix[i, j] = auc * 100
                    print(
                        f"  vs {generated_by}: TPR={tpr*100:.1f}%, AUC={auc*100:.1f}%"
                    )
                else:
                    tpr_matrix[i, j] = np.nan
                    auc_matrix[i, j] = np.nan
                    print(f"  vs {generated_by}: FAILED")

        print()

    return tpr_matrix, auc_matrix


def plot_tpr_table(tpr_matrix, models, score_metric="icas", target_fpr=0.01):
    fig, ax = plt.subplots(figsize=(12, 10))

    # models to skip
    skip = {"real", "taming", "llamagenl", "imagenet_val", "imagenet_train"}

    # indices to delete
    remove_rows = [i for i, m in enumerate(models) if m.lower() in skip]

    # delete rows ALL AT ONCE (critical!)
    tpr_matrix_filtered = np.delete(tpr_matrix, remove_rows, axis=0)

    # remaining row labels
    row_labels = [m for m in models if m.lower() not in skip]

    # build annotations
    annot = np.empty_like(tpr_matrix_filtered, dtype=object)
    for i in range(tpr_matrix_filtered.shape[0]):
        for j in range(tpr_matrix_filtered.shape[1]):
            if np.isnan(tpr_matrix_filtered[i, j]):
                annot[i, j] = "N/A"
            elif row_labels[i] == models[j]:
                annot[i, j] = "—"
            else:
                annot[i, j] = f"{tpr_matrix_filtered[i, j]:.1f}"

    mask = np.isnan(tpr_matrix_filtered)

    sns.heatmap(
        tpr_matrix_filtered,
        annot=annot,
        fmt="",
        cmap="RdYlGn",
        xticklabels=models,
        yticklabels=row_labels,
        vmin=0,
        vmax=100,
        cbar_kws={"label": "TPR (%)"},
        ax=ax,
        mask=mask,
    )

    ax.set_xlabel("Generated By (Non-Belonging Class)")
    ax.set_ylabel("Tested Model (Belonging Class)")
    ax.set_title(f"TPR@{target_fpr*100:.0f}%FPR ({score_metric.upper()})")

    plt.tight_layout()
    plt.show()
    return fig


def plot_auc_table(auc_matrix, models, score_metric="icas"):
    """Plot the AUC table as a heatmap"""
    fig, ax = plt.subplots(figsize=(12, 10))

    # Filter out "Real" from rows only (keep in columns)
    real_idx = [i for i, m in enumerate(models) if m.lower() == "real"]
    if real_idx:
        real_idx = real_idx[0]
        # Remove Real row only
        auc_matrix_filtered = np.delete(auc_matrix, real_idx, axis=0)
        row_labels = [m for m in models if m.lower() != "real"]
    else:
        auc_matrix_filtered = auc_matrix
        row_labels = models

    # Create annotations
    annot = np.empty_like(auc_matrix_filtered, dtype=object)
    for i in range(auc_matrix_filtered.shape[0]):
        for j in range(auc_matrix_filtered.shape[1]):
            if np.isnan(auc_matrix_filtered[i, j]):
                annot[i, j] = "N/A"
            elif row_labels[i] == models[j]:  # Check if diagonal
                annot[i, j] = "—"
            else:
                annot[i, j] = f"{auc_matrix_filtered[i, j]:.1f}"

    # Plot heatmap
    mask = np.isnan(auc_matrix_filtered)
    sns.heatmap(
        auc_matrix_filtered,
        annot=annot,
        fmt="",
        cmap="RdYlGn",
        xticklabels=models,
        yticklabels=row_labels,
        vmin=0,
        vmax=100,
        cbar_kws={"label": "AUC (%)"},
        ax=ax,
        square=False,
        mask=mask,
    )

    ax.set_xlabel("Non-Belonging Class (Generated By)", fontsize=12)
    ax.set_ylabel("Belonging Class (Tested Model)", fontsize=12)
    ax.set_title(
        f"AUC Detection Performance ({score_metric.upper()})", fontsize=14, pad=20
    )

    plt.tight_layout()
    plt.show()

    return fig
